### ISSUE TITLE
List Indices

### ISSUE THREAD

**Issue by asummers** [shhavel/uri_query#2]
I have a branch locally that adds indices to lists. Is this something of interest to the project? So for example 

```
%{a: %{b: [%{c: 1}, %{c: 2}]}}
```
becomes 
```
a[b][0][c]=1&a[b][1][c]=2
```

**Comment by asummers** [comment]
The implementation can be seen [here](https://github.com/shhavel/uri_query/compare/master...asummers:add-indices). Tests are currently not passing with this new addition, but I can address that if it's something you want mainline.

**Comment by shhavel** [comment]
Merged #3. Thank you.
